version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
  postgres:
    container_name: postgres
    image: postgres:12.3
    ports:
      - 5432:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      POSTGRES_DB: kgs
  api:
    container_name: api
    image: staskosatkin/kgs-api
    ports:
      - 8082:8080
    depends_on:
      - postgres
      - redis
  worker:
    image: kgs-worker
    build:
      context: .
      dockerfile: docker/worker.dockerfile
    container_name: worker
    working_dir: /var/www
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/var/www
    env_file:
      - .env
  scheduler:
    image: kgs-scheduler
    build:
      context: .
      dockerfile: docker/scheduler.dockerfile
    container_name: scheduler
    working_dir: /var/www
    depends_on:
      - redis
    volumes:
      - .:/var/www
    env_file:
      - .env

volumes:
  data-redis:
    driver: "local"
  data-postgres:
    driver: "local"

